artifact_uri: file:C:/Users/rapro/projects/MLOps/mlops-cloud-project-mlops-2/None/768985792482371169/c5c158fefee542598fbefc689058a41d/artifacts
end_time: 1759660010459
entry_point_name: ''
experiment_id: '768985792482371169'
lifecycle_stage: active
run_id: c5c158fefee542598fbefc689058a41d
run_name: LGBM_fit
source_name: ''
source_type: 4
source_version: ''
start_time: 1759660003063
status: 3
tags: []
user_id: rapro
