artifact_location: file:C:/Users/rapro/projects/MLOps/mlops-cloud-project-mlops-2/None/0
creation_time: 1759579639901
experiment_id: '0'
last_update_time: 1759579639901
lifecycle_stage: active
name: Default
