artifact_location: file:C:/Users/rapro/projects/MLOps/mlops-cloud-project-mlops-2/None/768985792482371169
creation_time: 1759579639926
experiment_id: '768985792482371169'
last_update_time: 1759579639926
lifecycle_stage: active
name: spotipy_recommender
