# Streamlit이 앱 내부에서 st.secrets["app"]["api_base"] 등으로 접근 가능하도록 설정
[app]
API_BASE = "http://music_recommender_api:8000"
RECO_LOG_FALLBACK = "./logs/reco_logs.csv"

# DB 정보는 보안을 위해 별도 섹션으로 분리
[database]
MYSQL_HOST = "114.203.195.166"
MYSQL_USER = "root"
MYSQL_PASSWORD = "root"
MYSQL_DB = "mlops"
MYSQL_PORT = "3306"